version: 4
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost:1883
  user: "!secret mqtt_user"
  password: "!secret mqtt_password"
serial:
  rtscts: true
  port: tcp://10.1.10.85:6638
  adapter: zstack
  baudrate: 115200
advanced:
  log_level: info
  channel: 11
  network_key: "!secret network_key"
  pan_id: 52132
  ext_pan_id:
    - 181
    - 37
    - 151
    - 219
    - 255
    - 162
    - 105
    - 125
frontend:
  enabled: true
  port: 8099
homeassistant:
  enabled: true
onboarding: true
